package com.VsmartEngine.Chatbot.Chat;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.Map;

/**
 * ChatApiController
 * =================
 * Exposes POST /api/chat/message — the REST entry-point that the
 * chatbot widget calls on every visitor message.
 *
 * The widget (generated by ScriptGenerateController) sends:
 *   { "sender": "email", "message": "...", "sessionId": "...", "departmentId": 1 }
 *
 * This controller delegates to RagProxyService which:
 *   → Calls Python RAG
 *   → Returns AI answer  (mode = "AI")
 *   → OR creates PENDING session + pushes WebSocket to agents  (mode = "PENDING")
 */
@CrossOrigin
@RestController
@RequestMapping("/api/chat")
public class ChatApiController {

    @Autowired
    private RagProxyService ragProxyService;

    /**
     * POST /api/chat/message
     *
     * Request body (JSON):
     * {
     *   "message":      "What are your prices?",
     *   "sender":       "visitor@email.com",
     *   "sessionId":    "abc-123",        ← optional (null on very first message)
     *   "departmentId": 1                 ← optional
     * }
     *
     * Response (JSON):
     * {
     *   "mode":      "AI",                       ← or "PENDING"
     *   "response":  "Our prices start at ...",
     *   "sessionId": "abc-123"
     * }
     */
    @PostMapping("/message")
    public ResponseEntity<Map<String, Object>> handleMessage(
            @RequestBody Map<String, Object> body) {

        String sender    = (String) body.getOrDefault("sender",    "anonymous");
        String message   = (String) body.getOrDefault("message",   "");
        String sessionId = (String) body.get("sessionId");

        Long deptId = null;
        if (body.get("departmentId") != null) {
            deptId = Long.valueOf(body.get("departmentId").toString());
        }

        if (message.isBlank()) {
            return ResponseEntity.badRequest().build();
        }

        Map<String, Object> result = ragProxyService.handleMessage(
                sender, message, deptId, sessionId);

        return ResponseEntity.ok(result);
    }
}
